### ISSUE TITLE
App stops when screen is goes to sleep, requiring a restart of the app

### ISSUE THREAD

**Issue by D3VL-Jack** [jlucidar/fpv_viewer_android#3]
When the device screen turns off the following error is thrown

```
2021-05-13 21:02:58.872 21619-13521/com.example.ijdfpvviewer E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.maybeThrowPrepareError(ProgressiveMediaPeriod.java:243)
        at com.google.android.exoplayer2.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:154)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:965)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 

```

[Full Logcat Dump](https://github.com/fpvout/fpv_viewer_android/files/6474812/log.txt)

**Comment by D3VL-Jack** [comment]
The app correctly handles being minimised
```
2021-05-13 21:10:59.289 12583-12583/com.example.ijdfpvviewer D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=false inTouchMode=true
2021-05-13 21:10:59.933 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: connecting to surface 0xb400007d3c3f3330, reason connectToSurface
2021-05-13 21:10:59.934 12583-15263/com.example.ijdfpvviewer I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 12884997
2021-05-13 21:10:59.934 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: disconnecting from surface 0xb400007d3c3f3330, reason connectToSurface(reconnect)
2021-05-13 21:10:59.934 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: connecting to surface 0xb400007d3c3f3330, reason connectToSurface(reconnect)
2021-05-13 21:10:59.935 12583-15264/com.example.ijdfpvviewer D/SurfaceUtils: set up nativeWindow 0xb400007d3c3f3330 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-05-13 21:10:59.936 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: disconnecting from surface 0xb400007d3c3fbb70, reason disconnectFromSurface
```

and opened again
```
2021-05-13 21:11:09.057 12583-12583/com.example.ijdfpvviewer D/RESUME_USB_CONNECTED: not connected
2021-05-13 21:11:09.077 12583-12583/com.example.ijdfpvviewer D/OpScreenModeManager: setRefreshRate parent androidx.constraintlayout.widget.ConstraintLayout{c4a5628 V.E...... ......ID 0,0-3120,1440} parent width 3120 parent height 1440 mRatio 1.2
2021-05-13 21:11:09.077 12583-12583/com.example.ijdfpvviewer D/OpScreenModeManager: setRefreshRate view android.view.SurfaceView{5ca5c4b V.E...... ......ID 0,0-3120,1440 #7f0a00df app:id/fpvView} viewRate 1 width 3120 height 1440
2021-05-13 21:11:09.082 12583-12583/com.example.ijdfpvviewer D/OpScreenModeManager: setRefreshRate parent androidx.constraintlayout.widget.ConstraintLayout{c4a5628 V.E...... ......ID 0,0-2910,1303} parent width 2910 parent height 1303 mRatio 1.2
2021-05-13 21:11:09.082 12583-12583/com.example.ijdfpvviewer D/OpScreenModeManager: setRefreshRate view android.view.SurfaceView{5ca5c4b V.E...... ......ID 0,0-2910,1303 #7f0a00df app:id/fpvView} viewRate 1 width 2910 height 1303
2021-05-13 21:11:09.083 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: connecting to surface 0xb400007d3c3f9960, reason connectToSurface
2021-05-13 21:11:09.083 12583-15263/com.example.ijdfpvviewer I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 12884998
2021-05-13 21:11:09.084 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: disconnecting from surface 0xb400007d3c3f9960, reason connectToSurface(reconnect)
2021-05-13 21:11:09.084 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: connecting to surface 0xb400007d3c3f9960, reason connectToSurface(reconnect)
2021-05-13 21:11:09.086 12583-15264/com.example.ijdfpvviewer D/SurfaceUtils: set up nativeWindow 0xb400007d3c3f9960 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-05-13 21:11:09.089 12583-15263/com.example.ijdfpvviewer D/SurfaceUtils: disconnecting from surface 0xb400007d3c3f3330, reason disconnectFromSurface
2021-05-13 21:11:09.091 12583-12583/com.example.ijdfpvviewer D/OpScreenModeManager: setRefreshRate parent androidx.constraintlayout.widget.ConstraintLayout{c4a5628 V.E...... ........ 0,0-2910,1303} parent width 2910 parent height 1303 mRatio 1.2
2021-05-13 21:11:09.091 12583-12583/com.example.ijdfpvviewer D/OpScreenModeManager: setRefreshRate view android.view.SurfaceView{5ca5c4b V.E...... ........ 0,0-2910,1303 #7f0a00df app:id/fpvView} viewRate 1 width 2910 height 1303
2021-05-13 21:11:09.101 12583-12583/com.example.ijdfpvviewer D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@cd70f41[MainActivity]
2021-05-13 21:11:09.102 12583-12583/com.example.ijdfpvviewer D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=true inTouchMode=true
```

**Comment by jlucidar** [comment]
is this still happening with alpha version ?

**Comment by fichek** [comment]
Doesn’t seem to be a problem anymore.

**Comment by jlucidar** [comment]
Closing this as it seems to not happen anymore.
